In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('data_sekolah.csv')

In [5]:
df.head()

      Nama_Siswa  Umur Kelas  Nilai_Ujian Status_Kelulusan
0   Agus Pratama  16.0  11-A         80.0            Lulus
1  Bunga Lestari  17.0  11-B         85.0            Lulus
2   Citra Kirana  16.0  11-A         90.0            Lulus
3  Dodi Setiawan  17.0  11-C         75.0            Lulus
4    Eka Saputri  16.0  11-B         88.0            Lulus

In [6]:
df.head(10)

      Nama_Siswa  Umur Kelas  Nilai_Ujian Status_Kelulusan
0   Agus Pratama  16.0  11-A         80.0            Lulus
1  Bunga Lestari  17.0  11-B         85.0            Lulus
2   Citra Kirana  16.0  11-A         90.0            Lulus
3  Dodi Setiawan  17.0  11-C         75.0            Lulus
4    Eka Saputri  16.0  11-B         88.0            Lulus
5    Feri Irawan  17.0  11-A         92.0            Lulus
6    Gita Gutawa  16.0  11-C         78.0            Lulus
7    Hadi Kusuma  17.0  11-B         85.0            Lulus
8  Intan Permata  16.0  11-A         95.0            Lulus
9    Joko Widodo  17.0  11-C         60.0      Belum Lulus

In [7]:
df.tail()

        Nama_Siswa  Umur Kelas  Nilai_Ujian Status_Kelulusan
115   Agus Pratama  16.0  11-A         80.0            Lulus
116  Bunga Lestari  17.0  11-B         85.0            Lulus
117   Citra Kirana  16.0  11-A         90.0            Lulus
118  Dodi Setiawan  17.0  11-C         75.0            Lulus
119    Eka Saputri  16.0  11-B         88.0            Lulus

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Nama_Siswa        120 non-null    object
 1   Umur              105 non-null    float64
 2   Kelas             120 non-null    object
 3   Nilai_Ujian       80 non-null     float64
 4   Status_Kelulusan  120 non-null    object
dtypes: float64(2), object(3)
memory usage: 4.8+ KB

In [9]:
df.describe()

             Umur  Nilai_Ujian
count  105.000000    80.000000
mean    16.495238    83.087500
std      0.502375     8.814823
min     16.000000    60.000000
25%     16.000000    78.000000
50%     16.000000    85.000000
75%     17.000000    90.000000
max     17.000000    96.000000

In [10]:
kolom_nama = df['Nama_Siswa']

kolom_nama.head()

0     Agus Pratama
1    Bunga Lestari
2     Citra Kirana
3    Dodi Setiawan
4      Eka Saputri
Name: Nama_Siswa, dtype: object

Nama_Siswa           0
Umur                15
Kelas                0
Nilai_Ujian         40
Status_Kelulusan     0
dtype: int64

Nama_Siswa          0
Umur                0
Kelas               0
Nilai_Ujian         0
Status_Kelulusan    0
dtype: int64

           Nama_Siswa  Umur Kelas  Nilai_Ujian Status_Kelulusan
30       Eross Candra   NaN  11-B         91.0            Lulus
31      Fatin Shidqia   NaN  11-C         77.0            Lulus
32      Gading Marten   NaN  11-A         89.0            Lulus
33  Hesti Purwadinata   NaN  11-B         93.0            Lulus
34        Irfan Hakim   NaN  11-C         65.0      Belum Lulus
35       Jihan Fahira  16.0  11-A          0.0      Belum Lulus
36          Kunto Aji  17.0  11-B          0.0      Belum Lulus
37          Luna Maya  16.0  11-C          0.0      Belum Lulus
38       Maudy Ayunda  17.0  11-A          0.0      Belum Lulus
39        Nola Tilaar  16.0  11-B          0.0      Belum Lulus

Rata-rata umur kelas ini adalah: 16.495238095238093

np.int64(5)